# Generated by Django - added DroppedRegistration model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=20)),
                ('student', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('parent', models.CharField(blank=True, max_length=100)),
                ('guardian', models.CharField(blank=True, max_length=100)),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('original_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
